# .prettierrc.yaml
trailingComma: "all"
tabWidth: 2
printWidth: 140
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
bracketSpacing: true
arrowParens: avoid
proseWrap: preserve
htmlWhitespaceSensitivity: css
endOfLine: auto
