Description: CloudFront distributions used for my-**** S3-based website redirects

Parameters:
  DomainName:
    Type: String
    Description: Domain name to be used for UI
  CertificateArn:
    Description: Optional Arn of ACM certificate
    Type: String
    AllowedPattern: ^(arn:aws:acm:us-east-1:[0-9]*:certificate\/[-a-z0-9]*)|()$ # arn:aws:acm:region:account-id:certificate/certificate-id
    Default: ""

Conditions:
  IsCertificateProvided: !Not [ !Equals [ !Ref CertificateArn, "" ] ]

Resources:
  My****Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      Tags:
        -
          Key: ****:project
          Value: my-****
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Enabled: True
        HttpVersion: http2
        Origins:
          -
            DomainName: !Sub '${DomainName}.s3.amazonaws.com'
            Id: srv-my****-s3
            S3OriginConfig: {}
        DefaultRootObject: "index.html"
        Logging:
          Bucket:
            Fn::Join:
              - ''
              - - !ImportValue ops-common-assets-CloudFrontAccessLogsBucket
                - .s3.amazonaws.com
          Prefix: !Ref DomainName
          IncludeCookies: True
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn:
            Fn::If:
              - IsCertificateProvided
              - !Ref CertificateArn
              - !ImportValue infra-cloudfront-acm-certificates-DefaultWildcardDeCertificate
        CustomErrorResponses:
          -
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: "/index.html"
            ErrorCachingMinTTL: 0
          -
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/index.html"
            ErrorCachingMinTTL: 0
        DefaultCacheBehavior:
          TargetOriginId: srv-my****-s3
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          Compress: True
          LambdaFunctionAssociations:
          - EventType: origin-response
            LambdaFunctionARN: !ImportValue ops-awsauto-set-security-headers-lambda-SecurityHeadersEdgeLambdaVersion

Outputs:
  DistributionDns:
    Value: !GetAtt My****Distribution.DomainName
    Description: DNS for CloudFront distribution
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", DistributionDns ] ]
  DistributionId:
    Value: !Ref My****Distribution
    Description: CloudFront distribution
    Export:
      Name: !Join [ "-", [ !Ref "AWS::StackName", DistributionId ] ]
